baseURL: http://fspaolo.net/
publishDir: docs
theme: hugo-paper
title: Fernando S. Paolo
copyright: Fernando Paolo 
summaryLength: 10

params:
    authorName: Fernando Paolo
    description: Fernando's awesome website 
    gitHubUser: fspaolo
    summaryLength: 10

permalinks:
    post: /:year/:month/:title/

menu:
    main:
    - name: My Work
      identifier: work
      url: /work/
      weight: -130

    - name: My Code
      identifier: code
      url: https://github.com/fspaolo
      weight: -120

    - name: To Reflect
      identifier: reflect
      url: /think/
      weight: -110

