baseURL: http://fspaolo.net/
publishDir: docs
theme: hugo-paper
title: Fernando S. Paolo
copyright: Fernando Paolo 

params:
    authorName: Fernando Paolo
    description: Fernando's awesome website 
    gitHubUser: fspaolo

permalinks:
    post: /:year/:month/:title/

menu:
    main:
    - name: Work
      identifier: work
      url: /work/
      weight: -130

    - name: Code
      identifier: code
      url: https://github.com/fspaolo
      weight: -120

    - name: Think
      identifier: reflect
      url: /think/
      weight: -110

