baseURL = "http://fspaolo.net/"
publishDir = "docs"
languageCode = "en"
title = "Fernando Paolo"
copyright = "Fernando Paolo"
theme = "sam"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "back to main"
    footerText           = ""

[[params.mainMenu]]
    link = "/work/research"
    text = "research"

[[params.mainMenu]]
    link = "/work/press"
    text = "press"

[[params.mainMenu]]
    link = "/work/pubs"
    text = "publications"

[[params.mainMenu]]
    link = "/think"
    text = "reflection"

[[params.mainMenu]]
    link = "/about"
    text = "who's fernando?"

[imaging]
    quality = 75
