[Settings]

[build]
  base = ""
  publish = "docs"
  command = "npm run build-prod"
  environment = { NODE_VERSION = "14.7.0", NPM_VERSION = "7.5.2" }

[context.deploy-preview]
  command = "npm run build-prod"

[context.develop]
  command = "npm run build"
